-- READ UNCOMMITTED (в pg автоматически повышается до READ COMMITTED)
-- Lost Update
BEGIN;
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

SELECT phone FROM Client WHERE ID = 1;

UPDATE Client SET phone = '+79998887766' WHERE ID = 1;
COMMIT;